### ISSUE TITLE
Replication code sample throwing errors

### ISSUE THREAD

**Issue by isolatedinformation** [cduck/VLQ#1]
When I try to run the result replication code sample as in the `README.md` file, it throws following error.

```
LoadError: ArgumentError: Package Tweaks not found in current path:
- Run `import Pkg; Pkg.add("Tweaks")` to install the Tweaks package.
```
The reference to Tweaks is in `make_plots.jl` line 38. A quick search of the `Tweaks.jl` package returned no useful package. How to solve this issue ?

**Comment by cduck** [comment]
Tweaks is a private package I use.  I thought I removed all references to it but I missed one.

I pushed a fix.  Please try again and let me know if it works.  I also added some more information to the install instructions that may help with any other issues.

**Comment by isolatedinformation** [comment]
1. It no longer throws that error. But a different error shows up.  
```bash
No handles with labels found to put in legend.
      From worker 2:       @ Distributed ./task.jl:411UndefVarError: make_noise_model_for_paper not defined
      From worker 2:    Stacktrace:
      From worker 2:     [1] everywhere_calc_single(plot_i::Int64, syndrome_sym::Symbol, d::Int64, e::Float64, override_key::Nothing, samples::Int64)
      From worker 2:       @ Main ~/quantum-playground/vlq/src/make_plots.jl:58
      From worker 2:     [2] macro expansion
      From worker 2:       @ ./timing.jl:368 [inlined]
      From worker 2:     [3] _do_work(jobs::RemoteChannel{Channel{Tuple{Any, Function, Any}}}, results::RemoteChannel{Channel{Pair{Tuple{Any, Any}, Tuple}}})
      From worker 2:       @ Main ~/quantum-playground/vlq/src/jobs.jl:81
      From worker 2:     [4] (::Distributed.var"#114#116"{Distributed.RemoteDoMsg})()
      From worker 2:       @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:299
      From worker 2:     [5] run_work_thunk(thunk::Distributed.var"#114#116"{Distributed.RemoteDoMsg}, print_error::Bool)
      From worker 2:       @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:63
      From worker 2:     [6] (::Distributed.var"#113#115"{Distributed.RemoteDoMsg})()

```
From what I understand, the worker node is not recognizing the includes statements in `vlq.jl`.
I do not have experience with `Distributed.jl` package and do not know why this is popping up

2. In line 36 in `make_plots.jl` should be modified to 
```julia
eval(:(@everywhere :(
        include("src/vlq.jl");
        using .VLQ.BiMaps
    )))
``` 
adding the `:` after the `@everywhere` as it expects an expression

**Comment by cduck** [comment]
-2. I believe it is correct without that `:`.  `@everywhere` is a macro so it already gets the expression.

-1. I had trouble setting this up the first time as well.  You run the code from the `vlq` environment but the worker processes are started in the global environment without those packages.  Try step 4 installing those packages globally.

**Comment by cduck** [comment]
I updated step 4 to also install VLQ globally for the workers.  See if that helps.

**Comment by isolatedinformation** [comment]
Let me check and get back to you.

**Comment by cduck** [comment]
OK.  There may be something you need to add to the path for workers.  Or you may also need to change the lines
```julia
        include("src/vlq.jl");
        using .VLQ.BiMaps
```
to
```julia
        import VLQ;
        using VLQ.BiMaps
```

**Comment by isolatedinformation** [comment]
The code sample in the `README.md` is working on my local pc now. The updated instructions were helpful. But I still had to make a couple of local changes to make it work. 

1. I am running it in Julia 1.6.2 instead of Julia 1.4.2. After instantiating the project I had to `Pkg.update()` once for the `PyPlot` to not throw precompilation errors. 
2. For the `Pkg.update()` to work, I had to rename `vlq.jl` to `VLQ.jl`, as Julia was throwing error could not find `src/VLQ.jl` for module `VLQ`

After these local changes, I ran the code sample and it generated the graphs without an error. 

But I have a **question**. 
Instead of running the workers globally, is there a way to run those instances inside the `vlq` environment. Say with the following code snippet, 
```julia
eval(:(@everywhere :(
        using Pkg; Pkg.activate("/path/to/vlq");
        include("src/vlq.jl");
        using .VLQ.BiMaps
    )))
```
I have not tried it, but wanted to know if there is a particular reason, the workers are run globally.

**Comment by cduck** [comment]
Great.  I'll see if I can incorporate that into the instructions.

I'm not sure why the workers run in the global environment.  Let me know if that hack works or anything else you find.

**Comment by isolatedinformation** [comment]
So I tried that hack and it works, but it seems take a lot of time for the workers to activate the environment. See image below
![image](https://user-images.githubusercontent.com/27089492/128628346-6ef3f1ac-4588-4317-bf72-4640f7272e83.png)

But as you can see, the hack makes the workers run in the environment at `/path/to/vlq`, but there seems to be a trade off for time to activate the environment for all the workers. The second time I ran it, it took >3 mins for the workers `setup`. Although it works, I think it is better off, as of now, at least to run the workers globally.

**Comment by isolatedinformation** [comment]
I guess, the exponential time increase has to do with the `Distibuted` package running workers in environments. We could confirm it by checking the hack in your local repo, but I guess it is not worth it.
